version: '3.3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080" 
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger  
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/swagger/swagger.yaml 